### ISSUE TITLE
wrong library name 'metaparse' in the --with-<library> option.

### ISSUE THREAD

**Issue by ludaye123** [faithfracture/Apple-Boost-BuildScript#29]
I use ./boost.sh -ios --boost-version 1.67.0 --boost-libs all --min-ios-version 9.0

but get a error
error: wrong library name 'metaparse' in the --with-<library> option.

What should I do？ Please

**Comment by faithfracture** [comment]
It looks the available compiled libraries have changed, some additions & some removals, metaparse being one of them. I'll need to update the script so that `--boost-libs all` works correctly for Boost 1.67.

There's a couple other things that probably need to happen with the update, so it's not going to be a quick turn around. In the meantime, you can run the script like this to get a build of version 1.67.0 with all the available libraries.

`./boost.sh -ios --boost-version 1.67.0 --min-ios-version 9.0 --boost-libs "atomic chrono container context contract coroutine date_time exception fiber filesystem graph graph_parallel iostreams locale log math mpi program_options python random regex serialization signals stacktrace system test thread timer type_erasure wave"`

**Comment by ludaye123** [comment]
Awesome, Thanks for your reply!
